name: bullseye
description: "A dart tracking application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  google_fonts: ^6.1.0
  provider: ^6.0.5

  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/target.png
    - assets/google.png
    - assets/apple.png
